### PR TITLE
 Create Greetings

### PR DESCRIPTION
**Pull request by Enoisong**
## Branch changes

- [ ] Create API endpoints for greeting texts
 
- [ ] [Link to Front-end]( https://github.com/Enoisong/hello_react_frontend)

### CODE REVIEW

**Review by abdulhamiid — CHANGES_REQUESTED** [review]
Hi @Enoisong 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] In the README file for the fronted, Please add a link to the `backend par`t 👍

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by abdulhamiid — CHANGES_REQUESTED** [review]
Hi @Enoisong 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] In the README file for the fronted, Please add a link to the backend part 👍

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Enoisong** [comment]
## Hi @abdulhamiid, 

  Thank you for reaching me. But please, I want to remark that I had already added a link to the ``Backend`` in the `Frontend` readme file. _Here👇 is the extract_:, 

 
# 📖 hello_react_frontend_app<a name="about-project"></a> 

> **[hello_react_frontend]** is a react app designed to consume API endpoint provided by [hello_rails_backend](https://github.com/Enoisong/hello_rails_backend/tree/greetings) to display greetings.



I appreciate.

**Review by Davidosky007 — APPROVED** [review]
Hi @Enoisong 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* API works well 👍 
* Well-written PR 👍 
* Random greetings work well 👍 
* No linter errors 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
